version: "3.7"
services:
  registry:
    image: registry:2
    restart: always
    networks:
      - host-bridge
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry
networks:
  host-bridge:
    driver: bridge
volumes:
  registry_data: